# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HCgc8J4Pb8KFEeWZrATQ4STuQTiTUbL8
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Page config
st.set_page_config(page_title="Burtin's Antibiotic Data Story", layout="wide")

# ---- Title ----
st.title("Exploring Antibiotic Effectiveness Through Burtin's Dataset")
st.caption("By Josiah Kondo - June 9, 2025")

# ---- Introduction ----
st.markdown("""
### What Can We Learn from This Data?

This dataset, visualized by Will Burtin in the 1950s, tracks the **minimum inhibitory concentration (MIC)** of three antibiotics - **Penicillin, Streptomycin, and Neomycin** - against **16 different bacterial species**.
MIC is the lowest concentration of an antibiotic needed to inhibit bacterial growth; simply put, **lower = more effective**.

Analysis of the data reveals a striking insight: **Gram-negative bacteria are substantially more resistant to Penicillin than Gram-positive bacteria.**
""")

# ---- Data ----
data = [
    {"Bacteria": "Aerobacter aerogenes", "Penicillin": 870, "Streptomycin": 1, "Neomycin": 1.6, "Gram_Staining": "negative"},
    {"Bacteria": "Bacillus anthracis", "Penicillin": 0.001, "Streptomycin": 0.01, "Neomycin": 0.007, "Gram_Staining": "positive"},
    {"Bacteria": "Brucella abortus", "Penicillin": 1, "Streptomycin": 2, "Neomycin": 0.02, "Gram_Staining": "negative"},
    {"Bacteria": "Diplococcus pneumoniae", "Penicillin": 0.005, "Streptomycin": 11, "Neomycin": 10, "Gram_Staining": "positive"},
    {"Bacteria": "Escherichia coli", "Penicillin": 100, "Streptomycin": 0.4, "Neomycin": 0.1, "Gram_Staining": "negative"},
    {"Bacteria": "Klebsiella pneumoniae", "Penicillin": 850, "Streptomycin": 1.2, "Neomycin": 1, "Gram_Staining": "negative"},
    {"Bacteria": "Mycobacterium tuberculosis", "Penicillin": 800, "Streptomycin": 5, "Neomycin": 2, "Gram_Staining": "negative"},
    {"Bacteria": "Proteus vulgaris", "Penicillin": 3, "Streptomycin": 0.1, "Neomycin": 0.1, "Gram_Staining": "negative"},
    {"Bacteria": "Pseudomonas aeruginosa", "Penicillin": 850, "Streptomycin": 2, "Neomycin": 0.4, "Gram_Staining": "negative"},
    {"Bacteria": "Salmonella (Eberthella) typhosa", "Penicillin": 1, "Streptomycin": 0.4, "Neomycin": 0.008, "Gram_Staining": "negative"},
    {"Bacteria": "Salmonella schottmuelleri", "Penicillin": 10, "Streptomycin": 0.8, "Neomycin": 0.09, "Gram_Staining": "negative"},
    {"Bacteria": "Staphylococcus albus", "Penicillin": 0.007, "Streptomycin": 0.1, "Neomycin": 0.001, "Gram_Staining": "positive"},
    {"Bacteria": "Staphylococcus aureus", "Penicillin": 0.03, "Streptomycin": 0.03, "Neomycin": 0.001, "Gram_Staining": "positive"},
    {"Bacteria": "Streptococcus fecalis", "Penicillin": 1, "Streptomycin": 1, "Neomycin": 0.1, "Gram_Staining": "positive"},
    {"Bacteria": "Streptococcus hemolyticus", "Penicillin": 0.001, "Streptomycin": 14, "Neomycin": 10, "Gram_Staining": "positive"},
    {"Bacteria": "Streptococcus viridans", "Penicillin": 0.005, "Streptomycin": 10, "Neomycin": 40, "Gram_Staining": "positive"},
]

df = pd.DataFrame(data)

# ---- Narrative Insight ----
st.markdown("""
---
### Narrative: Penicillin Fails Where Gram-Negative Walls Stand

The most compelling message from this dataset is simple but compelling: **Penicillin's effectiveness drops dramatically against Gram-negative bacteria.**
The reason seems to be that Gram-negative bacteria have an outer membrane that acts as a shield, keeping many antibiotics out.

In contrast, **Gram-positive bacteria** - with their simpler cell walls - are highly sensitive to even low doses of Penicillin.
This structural difference provides a lens with which to interpret MIC data.
""")

# ---- Antibiotic Selector ----
antibiotic = st.selectbox("Select an antibiotic:", ["Penicillin", "Streptomycin", "Neomycin"])

# ---- Sort for Consistent Gram Stain Order ----
gram_order = ["positive", "negative"]
df_sorted = df.sort_values(by=["Gram_Staining", antibiotic], ascending=[True, False])

# ---- Chart 1: MIC by Bacteria ----
st.subheader(f"{antibiotic} MIC by Bacterium and Gram Stain")
fig = px.bar(
    df_sorted,
    x=antibiotic,
    y="Bacteria",
    orientation="h",
    color="Gram_Staining",
    log_x=True,
    color_discrete_map={"positive": "skyblue", "negative": "salmon"},
    category_orders={"Gram_Staining": gram_order},
    title=f"Minimum Inhibitory Concentration (MIC) of {antibiotic} (Log Scale)"
)
fig.update_layout(
    xaxis_title="MIC (Minimum Inhibitory Concentration, log scale)",
    yaxis_title="",
    legend_title="Gram Stain"
)
st.plotly_chart(fig, use_container_width=True)

# ---- Chart 2: Box Plot by Gram Stain ----
st.subheader("Comparing Resistance Distributions by Gram Stain")
fig2 = px.box(
    df,
    x="Gram_Staining",
    y=antibiotic,
    color="Gram_Staining",
    log_y=True,
    color_discrete_map={"positive": "skyblue", "negative": "salmon"},
    title=f"Distribution of {antibiotic} MIC Values by Gram Staining",
    category_orders={"Gram_Staining": gram_order}
)
fig2.update_layout(yaxis_title="MIC (log scale)", xaxis_title="Gram Stain", showlegend=False)
st.plotly_chart(fig2, use_container_width=True)

# ---- Why It Matters ----
st.markdown("""
---
### Why This Matters
- **Penicillin**, one of the earliest antibiotics, is often ineffective against **Gram-negative pathogens**.
- This resistance stems not from genetic mutation but from a **biological structural difference**.
- These insights could help modern clinicians choose drugs more wisely and explain why Gram-negative infections are harder to treat.
""")

# ---- Closing Insight ----
st.markdown("""
---
### Final Takeaway

This interactive data story blends historical data, scientific insight, and visualizations to ultimately offer a clear message:

> **Know the enemy's walls!**

Gram stain isn’t just a lab technique - it is key to decoding antibiotic strategy for the future.
""")